name: Code Analysis and Security Assesment
 
on:
  pull_request:
    branches:
      - development
 
defaults:
  run:
    working-directory: /var/www/vhosts/www.strollay.com/gitaction
 
env:
  CHANGE_BRANCH: ${{ github.event.pull_request.head.ref }}
  CHANGE_TARGET: ${{ github.event.pull_request.base.ref }}
 
jobs:
  php_static_analysis:
    runs-on: gstech
    steps:
      - name: Checkout Target repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}
      - name: Checkout Source repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set CHANGED_FILES
        run: |
          cd $GITHUB_WORKSPACE
          echo 'pwd'
          git fetch origin
          git checkout ${{ env.CHANGE_TARGET }}
          git pull origin ${{ env.CHANGE_TARGET }}
          git checkout ${{ env.CHANGE_BRANCH }}
          git pull origin ${{ env.CHANGE_BRANCH }}
          changedFiles=$(git diff --name-only --diff-filter=ACMRT origin/${{ env.CHANGE_TARGET }}..origin/${{ env.CHANGE_BRANCH }})
          if [ ! -z "$changedFiles" ]; then
          CHANGED_FILES=$(echo "$changedFiles" | awk '{printf " --files %s", $0}')
          echo "CHANGED_FILES=${CHANGED_FILES}" >> $GITHUB_ENV
          else
            echo "No changed files in the pull request"
            echo "CHANGED_FILES=" >> $GITHUB_ENV
          fi
          echo $CHANGED_FILES
